name: biome

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    run:
        name: biome lint

        runs-on: ubuntu-latest

        timeout-minutes: 6

        steps:
            - uses: actions/checkout@v5
            - uses: biomejs/setup-biome@v2
              with:
                  version: latest

            - name: lint
              run: biome lint
