name: typos

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    run:
        name: typos

        runs-on: ubuntu-latest

        timeout-minutes: 6

        steps:
            - uses: actions/checkout@v4

            - name: typos
              uses: crate-ci/typos@master
